### ISSUE TITLE
"NAME" property collision

### ISSUE THREAD

**Issue by ebpa** [tj64/org-dp#3]
org-dp appears to conflate heading properties named "name" with the "#+NAME" element label.

This code:
```
(let ((hl (progn
        (outline-previous-heading)
        (org-element-context))))
  (org-dp-rewire
   nil ;; type.
   (buffer-substring (org-element-property :contents-begin hl)
             (org-element-property :contents-end hl))
   t ;; replace
   '(:title "new headline")
   hl))
```

Prepends a `#+NAME:` keyword with the value for property "name" (case-insensitive) before the headings itself.

```
* Test heading
:PROPERTIES:
:name: Foobar
:END:
```
Becomes:
```
#+NAME: PropertyValue
* new headline
:PROPERTIES:
:name: Foobar
:END:
```
instead of:
```
* new headline
:PROPERTIES:
:name: Foobar
:END:
```

FWIW, here are org parse trees (8.3.4) to show the problem isn't with the org ast:
```
* Test heading
:PROPERTIES:
:name: Foobar
:END:
```
```
(org-data
 nil
 (headline
  (:raw-value "Test heading" :begin 1 :end 49 :pre-blank 0 :contents-begin 16 :contents-end 49 :level 1 :priority nil :tags nil :todo-keyword nil :todo-type nil :post-blank 0 :footnote-section-p nil :archivedp nil :commentedp nil :post-affiliated 1 :NAME "Foobar" :title (#("Test heading" 0 12 (:parent #1))) :parent #0)
  (section
   (:begin 16 :end 49 :contents-begin 16 :contents-end 49 :post-blank 0 :post-affiliated 16 :parent #1)
   (property-drawer
    (:begin 16 :end 49 :contents-begin 29 :contents-end 43 :post-blank 0 :post-affiliated 16 :parent #2)
    (node-property (:key "name" :value "Foobar" :begin 29 :end 43 :post-blank 0 :post-affiliated 29 :parent #3))))))
```
```
#+NAME: Bazbat
* Test heading
:PROPERTIES:
:name: Foobar
:END:
```
```
(org-data
 nil
 (section
  (:begin 1 :end 16 :contents-begin 1 :contents-end 16 :post-blank 0 :post-affiliated 1 :parent #0)
  (keyword (:key "NAME" :value "Bazbat" :begin 1 :end 16 :post-blank 0 :post-affiliated 1 :parent #1)))
 (headline
  (:raw-value "Test heading" :begin 16 :end 64 :pre-blank 0 :contents-begin 31 :contents-end 64 :level 1 :priority nil :tags nil :todo-keyword nil :todo-type nil :post-blank 0 :footnote-section-p nil :archivedp nil :commentedp nil :post-affiliated 16 :NAME "Foobar" :title (#("Test heading" 0 12 (:parent #1))) :parent #0)
  (section
   (:begin 31 :end 64 :contents-begin 31 :contents-end 64 :post-blank 0 :post-affiliated 31 :parent #1)
   (property-drawer
    (:begin 31 :end 64 :contents-begin 44 :contents-end 58 :post-blank 0 :post-affiliated 31 :parent #2)
    (node-property (:key "name" :value "Foobar" :begin 44 :end 58 :post-blank 0 :post-affiliated 44 :parent #3))))))
```

This was originally observed with org 8.3.4 and 20160326.603, but @jkitchin confirms the problematic behavior occurs under org 9.

Original discussion: http://emacs.stackexchange.com/questions/29128/programmatically-setting-an-org-mode-heading/29129#29129

**Comment by tj64** [comment]
Hi, sorry, I missed this ...
The interesting question would be, if the same happens with different keys like e.g. "home" or "office" instead of "name".
I'm not sure, but may this is just the org-element interpreter being smart with special affiliated keyword "name" or so?

**Comment by ebpa** [comment]
No worries :+1: 

Digging into this again...  You're right.  The culprit is `org-element-at-point`.  In spite of their distinct positions in the org AST, that function conflates the two properties when reporting the headline.  I had incorrectly assumed that the property was aliased within the org-dp logic.  I'll add this to my local list of beefs with org property logic and raise the issue with org when I've got a proposal for a fix.

~~You can close this as far as I'm concerned.~~ (closed)

Thanks for the time, @tj64 and kudos for the package!
